#!/bin/bash

obsidian_path=/home/syncthing/data/Obsidian
kp_path=/home/syncthing/data/Passwords


tar --zstd -cf obsidian.zst $obsidian_path
gpg --encrypt --recipient data obsidian.zst
rm obsidian.zst

tar --zstd -cf kp.zst $kp_path 
gpg --encrypt --recipient data kp.zst 
rm kp.zst

git add .
git commit -m "$(date)"
git push -u origin main

